- lakeshore370.py
Changed the lakeshore_370 server to read at a set speed.
> 25 lakeshore upgrade

- gpib_server.py
> Changed gpib_server to use read_raw instead of

- GHzDACs/Cleanup/dac.py
- GHzDACs/ghz_fpga_server.py
> Fix references to I2C_RB and I2C_ACK in dac.py

- Qubit Server/dev/testing/jqs_test.py
Otherwise the script gets discovered by pytest and it's not happy...
> Fix jqs_test script to run code inside a main method.

- GHzDACs/ghz_fpga_server.py
> Add more descriptive error message when unknown fpga builds are detected.

- dr_logger.py
Addresses #98 to some extent. More documentation still needed, but at least this regularizes the expected registry format.
NB: This commit changes the expected form of the registry entries for the dr logger (in a good way). See server docstring for expected registry format.
@pomalley
> Fix dr logger

- ghzdac_cal/GHz_DAC_calibrate.py
> Add documentation for GHzDAC calibration procedure.

- agilent_infiniium_scope.py
CH -> CHAN.
From the keysight programmers guide:
> infiniium server: bugfix in channel source write

- GHzDACs/ghz_fpga_server.py
Switches the BoardGroups to get context and connection from the
DE server every time before using either. Move the BoardGroup
Init call to aslo reinitialize existing BoardGroups on
DE server reconnecting.
Fixes #134
> Reinitialize BoardGroup's on Direct Ethernet restart.

- GHzDACs/Cleanup/dac.py
- QubitServer/build.sbt
- QubitServer/src/main/java/org/labrad/qubits/QubitContext.java
- QubitServer/src/main/java/org/labrad/qubits/QubitServer.java
- QubitServer/src/main/java/org/labrad/qubits/jumptable/JumpTable.java
- QubitServer/src/main/pack/QubitServer.ini
The QS is looking at the wrong index for converting the CYCLE command from number of cycles desired to counter index.
> Fix bug with wrong index of CYCLE argument processing.

- GHzDACs/ghz_fpga_server.py
Made while fixing #134 but held them back for a separate commit.
> Style cleanups for ghz_fpga_server.

- GHzDACs/test/test_fpga_server.py
It seems that the test was written assuming an IDLE time offset
of -1, but in GHzDACs.Cleanup.dac.DAC_Build15 there is:
JT_IDLE_OFFSET = -0
Fixes #162.
> Fix the failing ghz_fpga_test.

- GHzDACs/Cleanup/dac.py
- GHzDACs/ghz_fpga_server.py
Fill out docstrings for functions used in DAC LVDS and FIFO bringup.
> FPGA: Fill out docstrings for LVDS,FIFO Bringup

- DirectEthernet/README.md
- QubitServer/README.md
> Add readme files for scala servers describing how to build and install.

- agilent_DSO7104B.py
Tested on el-capitan at google.
> Add deviceName string for agilent 4104A scope

- DirectEthernet/build.sbt
> Add bintray resolver back to build.sbt

- DirectEthernet/build.sbt
- DirectEthernet/src/main/pack/DirectEthernet.ini
- DirectEthernet/src/main/scala/org/labrad/ethernet/server/EthernetBus.scala
> Wait for packet capture thread to start before returning from listen.

- serial_server.py
We need to open the serial port in nonblocking mode (timeout = 0).
> Fix for bug introduced with PR #240 (timeout error)

- GHzDACs/ghz_fpga_server.py
Also makes board group removal itself more robust by checking whether the direct ethernet server is still connected before trying to expire the board group context.
Fixes #235
This is an alternative to #237. @jwenner
> Catch and log exceptions when removing board groups.

- GHzDACs/ghz_fpga_server.py
> Fix timeout recovery to work with or without executionCount

- QubitServer/src/main/java/org/labrad/qubits/QubitContext.scala
Fixes #262.
@maffoo I think you're the only person around here qualified to judge scala code :P
> Document Get Data Raw in the qubit sequencer

- DirectEthernet/README.md
> Update direct ethernet readme with a note about log warnings

- QubitServer/src/main/scala/org/labrad/qubits/Experiment.scala
- QubitServer/src/main/scala/org/labrad/qubits/QubitContext.scala
- QubitServer/src/main/scala/org/labrad/qubits/util/Grouping.scala
> Show dev, channel and microwave config when configs conflict.

- ghz_fpga_server.py
The timeout recovery was failing due to the run context getting prematurely unlocked during timeout recovery. This was causing register pings to be interleaved with the next sequence run, causing cascading timeout failures that could bring scans to a halt. We fix this by waiting until after all boards have been pinged to send any triggers for failed boards.
In addition to the logic fix, also includes some minor cleanups of the timeout recovery and reporting code.
Dupe of #278 since that got merged accidentally before review
> Fix timeout recovery code in ghz_fpga_server.py

- mks_server.py
Add print statements to mks server for when returning NaN or min/max scale. When invalid data received, would set reading to one of these without indicating cause of error. If error present, also
print the pressure and full_scale readings so user can see what's happening.
With a 0.02s readout time, the mks server would start getting back corrupted data after a few minutes; this would then continue on as the buffer would not be cleared. Change readout time to 0.05s, which seems to be enough to fully read data out without leading to data corruption.
> Print mks errors. Change mks readout time.

- datavault/signals.md
> Add doc describing how data vault signals work

- data_vault.py
- data_vault_multihead.py
- datavault/__init__.py
> Sort directory and datasets names when getting datavault listing.

- DirectEthernet/LICENSE
- QubitServer/LICENSE
> Add explicit licenses for direct ethernet and qubit servers.

- fpgalib/dac.py
- fpgalib/fpga_test.py
- fpgalib/test/test_dac.py
> Test dacify and reduce loops through waveforms.

- agilent_33120a_function_gen.py
and for clearing the event register.  Tested on Vince.
> Added methods for Setting AC voltage and frequency
