martinisgroup/servers

GUIs/LabRADPlotWidget3.py
GUIs/SuperMonitor.py
GUIs/__init__.py
dr_logger.py
mks_server.py
serial_server.py

I've tried to make the DR logger better about handling dead servers and displaying errors.
I've also changed the serial and mks servers to make the MKS server report 0 when the gauges read "LO" and the full scale when "OFF". Having NaNs in the data vault is really annoying. If there is a serial error, though, there still will be NaNs so you know if something is broken.
This includes commits from #44 so that needs to happen first.

Fix dr logger

---

GUIs/ADR/ADRcontrol2.py
GUIs/ADR/LabRADPlotWidget2.py

There is now an option to hide checkboxes for un-watched lines, rather than showing them on mouseover (which turned out to be annoying). This fixes #21, finally.

ADR GUI checkbox hiding

---

GRAPE/GRAPE.py
GUIs/MBE/MBEStatus.py

These pyle imports were broken by recent refactoring in pyle, but also seem to be unnecessary. There's one remaining import in MBEStatus that is still used: datavault. It's unfortunate to have this dependency from servers on pyle. Maybe the datavault wrapper stuff should eventually be moved here to live with the data vault server?

Fix some imports broken by pyle registry refactor.

---

data_vault.py
data_vault_multihead.py

This setting imports a bunch of parameters from the registry by using the context of the given request and assuming that the same context has been set up with the registry. This sort of inter-server context synchronization is a bad idea and needs to go away. This setting is not actually being used, instead we usually just set parameters on our own using the registry wrapper, which is a much more sane way to go. Hence, removing this should be low impact.

Remove import_parameters setting on data_vault server.

---

Qubit Server/dev/src/main/java/org/labrad/qubits/QubitContext.java
Qubit Server/dev/src/main/java/org/labrad/qubits/channeldata/AnalogDataFourier.java
Qubit Server/dev/src/main/java/org/labrad/qubits/channeldata/AnalogDataTime.java
Qubit Server/dev/src/main/java/org/labrad/qubits/channeldata/IqDataFourier.java
Qubit Server/dev/src/main/java/org/labrad/qubits/channeldata/IqDataTime.java
Qubit Server/dev/src/main/java/org/labrad/qubits/channels/AnalogChannel.java
Qubit Server/dev/src/main/java/org/labrad/qubits/channels/IqChannel.java
Qubit Server/dev/src/main/java/org/labrad/qubits/proxies/DeconvolutionProxy.java
dac_calibration_server.py
ghzdac/correction.py
ghzdac/keys.py

The deconvolution server was mutating the user's waveform data without respect to any parameters passed into `Correct` or `Correct FT`:
* For Z waveforms, dithering had the appearance of being set by a boolean parameter on the context, but was actually being defaulted to `True` at context initialization! It was also optionally set by a global registry key for the entire server. This should be a per-request variable.
* For Z waveforms, averaging the first and last four SRAM samples was done without regard for any input parameters. This meant that there was *no way* to not have your pulse sequence mutated by the server.
* For IQ waveforms, zeroing the first and last four SRAM samples was done without regard for any input parameters. This meant that there was *no way* to not have your pulse …

Make averaging, dithering, and zeroing optional and off by default.

---

GHzDACs/ghz_fpga_server.py

Fixes #100.
In FPGA server/run (and hence run_sequence), if ADC in average mode so that no demod channel specified, raised 'channel format not understood' exception. Now add elif case in getTimingData so if ADC is present in channel name but not :: (for demodulation), can still return data. Move calls to channel to if statement for if channel defined. Amend return format type for run_sequence to also allow '*3i' for average mode data.
Note that in going between demod and average modes (although in different scans & calls to run_sequence), it seems to work fine (although it's possible I might not be seeing/knowing what @JulianSKelly was referring to).

GHzFPGA.run: Enable ADC Average Mode

---

GHzDACs/ghz_fpga_server.py

Previously, the result from run_sequence was being returned as a python list of numpy arrays, so that the special flattening code for numpy arrays was being bypassed. With this change, @JulianSKelly and I saw roughly a factor 2x increase in data throughput under load.

Convert run_sequence result to single numpy array before flattening.

---

GHzDACs/Cleanup/fpga.py
GHzDACs/ghz_fpga_server.py
GHzDACs/sequencer.py

The delphi direct ethernet server changes the 'shape' of packet responses when you try to read one versus multiple packets. In particular, if you call `.read()` it returns a single packet as `(ssis)`, but if you call `.read(1)` it returns a list of one packet as `*(ssis)`, which obviously is the same type used for larger numbers of packets as well. By changing all the read calls to specify the number of packets explicitly, we always get the same type back, which normalizes the response handling. In the new scala version of the direct ethernet server, this allows us to simplify the implementation since we can just specify a single return type.

Change ghz_fpga_server to always read a list of packets.

---

GHzDACs/GHzAD_v7.md

I typed up John's GHzAD v7 doc into a markdown file. This should make version control and reading easier. I propose we regard this as unofficial documentation. The official docs are always what's in John's directory, and we can make more readable versions for ourselves. Maybe that's a dumb idea. If so, please say so.

Document GHzAD version 7 in markdown file (probably easy)

---

GHzDACs/ghz_fpga_server.py

The server's recover from timeout strategy involves reading an execution counter form the boards. Unfortunately, not all boards support this and the server was failing on a `KeyError`.
Now we gracefully handle this case.
Tested running on Jules, got timeout, server reported execution counts and carried on!
Fixes #135.

Gracefully handle unavailable executionCount

---

cryo_notifier.py
lakeshore370.py

When building registry paths in some instance were were lower-casing the directory names and assuming the registry was case-insensitive, which was an artifact of the registry being a thin wrapper around the windows filesystem. In the new delphi implementation, registry paths are case sensitive. We had to make these changes to get the scala manager and registry proxy working on vince, er Vince.

Do not assume case-insensitivity when building registry paths.

---

GHzDACs/ghz_fpga_server.py

(Making PR so folks can tell me if I'm being high with this strategy)
We explicitly silence exceptions occuring during the board pings. This is ok because we have a finally clause to clear the packet buffers in the direct ethernet server.
Also increase number of retries for timeout errors.
The only thing left to do here (I think) is improve the error logging e.g. by adding time stamps.
Fixes #137.

Remove exception raised by recoverFromTimeout.

---

data_vault.py
data_vault_multihead.py
datavault/__init__.py
datavault/backend.py
datavault/errors.py
datavault/util.py
tests/config_datavault.py
tests/test_datavault.py

This includes the refactoring changes from #24 minus the binary data backend, and with the addition of the parameter evaluation fix from #149. This will give us a much better foundation to build on going forward (e.g. for hdf5 support) since we will not have to maintain parallel versions of the single- and multi-headed versions of the data vault.

Refactor data_vault and data_vault_multihead to share common code

---

DCRack/dc_rack_server.py

Some functions were decorated by `@inlineCallbacks` for no reason, so we remove that and convert associated `returnValue` calls to `return`.
Fixes #156.
(Might fix #139)

Fix synchronous versus asynchronous calls in dc Rack Server

---

data_vault.py

Allows the repository location to be specified with ~ and ~username
instead of just the full path. Fixes #144 and maffoo/scalabrad#2.

Expand "~" and "~username" in data_vault.

---

dac_calibration_server.py

Fourier data should clearly be complex, not real as was being advertised.

Fix accepted data type for analog IQ correction.

---

data_vault.py
data_vault_multihead.py
datavault/server.py

We move the code for these servers into the datavault package and make the server class for the multi-headed data vault into a subclass of the single-headed server class, so that the two can share the setting code. The server launch scripts are reduced basically just to shims that load some settings and then launch the server itself.
Depends on martinisgroup/pylabrad#114

Consolidate code shared by data_vault and data_vault_multihead

---

DirectEthernet/build.sbt
DirectEthernet/src/main/pack/DirectEthernet.ini
DirectEthernet/src/main/scala/org/labrad/ethernet/server/EthernetBus.scala
DirectEthernet/src/test/scala/org/labrad/ethernet/server/DirectEthernetTest.scala

Fixes #182 
I think this is probably worth having even if the firewall configuration changes fix the pcap errors. We will want to monitor the logs for any errors that crop up in case this happens frequently, but that's a whole other thing...

Keep pcap loop alive even if errors occur.

---

GHzDACs/Cleanup/adc.py

The check made assumptions about how higher level code would write the
trigger table. Since those assumptions are not necessarily correct and
because the check prevented valid use cases, we removed it.
@JulianSKelly for the sake of procedure can you LGTM this again?

Remove un-necessesary check in ADC trigger table creation.

---

ADR/ADR.py
QubitServer/src/main/java/org/labrad/qubits/QubitServer.java

Fix profane language in qubit sequencer and ADR servers. Fixes #207.

Fix profanity in ADR + qubit sequencer servers.

---

README.md

PyQt is needed by e.g. the fridge monitor. As it is not packaed for `pip`, we need a manual procedure for installation into a virtualenv. This commit provides that procedure.
It's possible that we could fix this up to work with pip, but I have not investigated that.

Explain how to install PyQt into a virtualenv on Linux

---

GHzDACs/GHz_DAC_bringup.py

Remove imports from msvcrt. The input code was already using `raw_input` anyway (which requires the user to press enter, so this does not change the behavior, just makes it more cross-platform.

Remove reference to windows-only getch

---

GHzDACs/ghz_fpga_server.py

The return signature for the LVDS MSD and MHD in dac_bringup was 'w', when these can return -1 if 0 or 2+ MSD/MHD bit flips. Change return signature to 'i'. Note this is correct in dac_lvds.
FYI @maffoo, this should probably also get dealt with in #226.
@afowler, this should hopefully fix your ScanPhases error (or at least lead to a later error).

Fix ghz_fpgas.dac_bringup return signature for LVDS MSD/MHD

---

DirectEthernet/src/test/scala/org/labrad/ethernet/server/TestUtils.scala

Fixes #230 
This at least fixes the test compilation problem. I still see issues with the tests themselves due to, for example, the fact that pcap requires administrator access on some platforms. These tests could thus use some additional work, but I'd like to tackle that as part of a separate issue.

Fix compilation error in DirectEthernet tests.

---

serial_server.py

We were using hard-coded COM port names from COM1..COM20.  This worked on Windows, but not on Linux or OSX.  pyserial has a built-in device name enumeration, but it might not work properly on windows.  So we keep the same detection code on windows, but use the pyserial built-in stuff on Linux and OSX.  I attempted to not change the windows code path, but don't have a good way to test it.  Can someone run this on windows and verify that list_serial_ports() and open() work properly?

Update serial server to work on Linux as well as windows (also OSX)

---

QubitServer/build.sbt
QubitServer/src/main/java/org/labrad/qubits/controller/JumpTableController.scala
QubitServer/src/main/java/org/labrad/qubits/controller/MemoryController.scala
QubitServer/src/main/pack/QubitServer.ini

Both these calls are not needed, since the instances in both cases are constructed in a 'cleared' state. The MemoryController call in particular was causing a NullPointerException because the clear call could be made before all fields were initialized.
Fixes #243

Remove unneeded calls to clear() in controller constructors.

---

DirectEthernet/build.sbt
DirectEthernet/src/main/pack/DirectEthernet.ini
DirectEthernet/src/main/scala/org/labrad/ethernet/server/DirectEthernet.scala

Use LabradException to avoid verbose tracebacks.

---

data_vault_multihead.py

Tested with both pre- and post-TLS pylabrad.  The multihead datavault needs to be updated because it doesn't use runServer()

Update datavault to support TLS

---

datavault/backend.py

Depends on labrad/pylabrad#160 to fix the handling of `None` for units. See that PR for more context. This hack is specific to data vault parameters, not needed for backwards compatibility of `evalLRData` itself, which is why I've put it here.

Fix eval of old parameters saved with 1.#IND for nan.

---

ghzdac/calibrate.py
ghzdac/keys.py
ghzdac_cal/GHz_DAC_calibrate.py

The AC Pulse calibration for the DACs assumes the use of a microwave switch. This PR adds a registry key to determine if a switch is present.
In addition, the final reset length was <20ns, the minimum jump table sequence length. This length is increased.

AC Pulse Cal - Allow for no switch

---

fpgalib/tools/ghz_fpgas.lua

This proved useful in tracking down the bug fixed in #279. There's still a lot that could be added--for example I haven't defined all the protocol fields and it would be nice to add some summary packet info in addition to the dissection tree--but I thought it'd be nice to commit this and others can contribute.

Add wireshark plugin for analyzing FPGA network traffic.

---

DirectEthernet/build.sbt

MAC address detection in pcap4j was recently fixed on windows (https://github.com/kaitoy/pcap4j/issues/49). This updates the library dependency to pick up the change.

Update pcap4j version to make MAC detection work on windows.

---

fpgalib/docs/GHzDAC_v8.md

We already have markdown version of the ADC docs, this adds it for the DACs as well. For now, I've just copied the content and done some simple markdown formatting. I have not yet changed the packet descriptions to be zero-indexed, as was done for the ADC docs. For all of our sanity we should do that before merging, but for now I'd like reviewers to just look at the basic formatting and compare the content to what's in the word doc. I'll make a separate change to fix the indexing.

Add markdown version of documentation for GHz DACs

---

fpgalib/dac.py
fpgalib/jump_table.py
fpgalib/test/test_dac.py

Fixes #323
Change error checking for when two jump table commands are executed too closely in time, rather than too closely in memory.

Fix unwanted exceptions from dac 15 class.

---

ghzdac/calibrate.py

Modify run_dac_sram call in calibrate to send 20 samples, due to changes in ghz fpga

---

datavault/backend.py
tests/test_datavault.py

The FlatData type is a namedtuple that replaces the plain tuple returned by older versions of pylabrad when flattening data. We modify the labrad_urlencode method to use names of the FlatData items if possible, rather than explicitly unpacking the tuple. This lets us maintain compatibility with changes in 0.95.2 which added a third endianness member to the FlatData tuple.

datavault: Fix labrad_urlencode to work with new FlatData type

---

spectrum_analyzer.py

Finally tracked down that intermittent error on the spectrum analyzer where it would fail one time out of 100 because of a lack on newline characters.

uses read_raw function to fix intermittent white space GPIB error.
